import type { NextPage } from 'next'
import Head from 'next/head'
import { useUser } from '@auth0/nextjs-auth0'
import axios from 'axios';

const Home: NextPage = () => {

  const { user, error, isLoading } = useUser();

  //console.log(user)

  axios.get('/api/profile', {
    withCredentials: true
  })
  .then((res) => console.log(res))

  if (isLoading) return <div>Loading...</div>;
  if (error) return <div>{error.message}</div>;
  if (!user) return <a href="/api/auth/login">Login</a>;
  return <div>Hello {user.name} <a href="/api/auth/logout">Log out</a></div>

  {/* return (
    <div>
      <Head>
        <title>Versed</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <p>My App</p>
      <a href="/api/auth/login">Login</a>
    </div>
  ) */}
}

export default Home
